### ISSUE TITLE
make a json string output to be able to generate matrix 

### ISSUE THREAD

**Issue by StepanKuksenko** [joao-zanutto/get-selected#2]
It would be grate to generate output in a json string format to generate matrix from it.  
Matrix generation from JSON documentation: https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object

**example:**
```yaml
on:
  workflow_dispatch:
    inputs:
      app1:
        description: 'Deploy app1'
        default: false
        type: boolean
      app2:
        description: 'Deploy app2'
        default: false
        type: boolean

jobs:
  get-selected:
    name: Get Selected Checkboxes
    runs-on: ubuntu-latest
    outputs: 
      selectedJson: ${{ steps.get-selected-step.outputs.selected}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Selected
        id: get-selected-step
        uses: joao-zanutto/get-selected@v1
        with:
          output: json

      - name: Consume on the same job
        run: echo ${{ steps.get-selected-step.outputs.selectedJson }}
        # '["app1", "app2"]'

  deploy-multiple-apps:
    needs: get-selected
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-selected.outputs.selectedJson) }}
     
```
